[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://promspec-5ydr.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
