services:
  - type: web
    name: prom-spec-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@promspecstroy.kz
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Portal Admin
      - key: CLIENT_URL
        value: "*"
